// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkvhZ4A6ZFbMiAgAMh0TeGCZ61urxs_yk',
    appId: '1:792677641794:web:9dbc2891befc017a0d87db',
    messagingSenderId: '792677641794',
    projectId: 'myfitnesstracker-857f7',
    authDomain: 'myfitnesstracker-857f7.firebaseapp.com',
    storageBucket: 'myfitnesstracker-857f7.appspot.com',
    measurementId: 'G-TRMFMCS52N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNX2K4QV5H6LD9CKCQAoB2Llc-j3znajk',
    appId: '1:792677641794:android:c8b08f77c433d04a0d87db',
    messagingSenderId: '792677641794',
    projectId: 'myfitnesstracker-857f7',
    storageBucket: 'myfitnesstracker-857f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBljQC6lqWva8x7UgGiXPXGqhET6V4Ux8w',
    appId: '1:792677641794:ios:31c1a9cffefeca730d87db',
    messagingSenderId: '792677641794',
    projectId: 'myfitnesstracker-857f7',
    storageBucket: 'myfitnesstracker-857f7.appspot.com',
    androidClientId: '792677641794-aue63rcpdvhjb839bqgcgl5fqbd3n4vf.apps.googleusercontent.com',
    iosBundleId: 'com.example.getFit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBljQC6lqWva8x7UgGiXPXGqhET6V4Ux8w',
    appId: '1:792677641794:ios:9d0caf6e4186a7c90d87db',
    messagingSenderId: '792677641794',
    projectId: 'myfitnesstracker-857f7',
    storageBucket: 'myfitnesstracker-857f7.appspot.com',
    androidClientId: '792677641794-aue63rcpdvhjb839bqgcgl5fqbd3n4vf.apps.googleusercontent.com',
    iosBundleId: 'com.example.getFit.RunnerTests',
  );
}
